# Generated by Django 3.1.2 on 2020-10-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('setting', models.PositiveSmallIntegerField(choices=[(1, 'Face to face'), (2, 'Online')], default=1)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.clients')),
            ],
        ),
    ]
