# Generated by Django 3.1.2 on 2020-11-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
