# Generated by Django 3.1.2 on 2020-11-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='clientID',
            new_name='client',
        ),
    ]
