# Generated by Django 3.1.2 on 2020-11-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20201107_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='event_date',
        ),
    ]
