# Generated by Django 3.1.2 on 2020-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20201110_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='receipt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
